name: generate-files
on:
  push:
    branches:
      - master
jobs:
  generate-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
      - name: Install required 'geocoder' gem
        run: gem install geocoder
      - name: Run JSON Generator
        run: ruby generateJSON.rb
      - name: Install required 'git' gem
        run: gem install git
      - name: Run Sitemap Generator
        run: ruby generateSitemap.rb
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Regenerate municipalities.json" || exit 0
          git push
